#ifndef INCLUDE_CRYSTALELEMENT_TEMPLATE_INSTANTIATIONS_H_
#define INCLUDE_CRYSTALELEMENT_TEMPLATE_INSTANTIATIONS_H_

#ifndef CRYSTALELEMENT_TEMPLATE_INSTANTIATION
#define CRYSTALELEMENT_TEMPLATE_INSTANTIATION
template class crystalElement<2>;
template class crystalElement<3>;
#endif

#endif /* INCLUDE_ELLIPTICBVP_TEMPLATE_INSTANTIATIONS_H_ */
